apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-app-backend-deployment
  labels:
    app: smtp-app-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-pod
    spec:
      containers:
        - name: smtp-app-backend
          image: smtp-app-backend:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: postgresql://admin:nimda@postgres-db-service:5432/smtp-sender-db?schema=public

---
apiVersion: v1
kind: Service
metadata:
  name: smtp-app-backend-service
  labels:
    app: smtp-app-backend-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: backend-pod
