version: "3.8"
services:
  smtp-sender-app:
    image: smtp-sender-app:1.0.0
    container_name: smtp-app
#    if image is not used
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .dev.env

  postgres:
    image: postgres
    container_name: smtp-app-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .db.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: smtp-sender-db
