version: "3.8"
services:
  smtp-app-backend:
    image: smtp-app-backend:1.0.0
    container_name: smtp-app-backend
    #    if image is not used
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - postgresdb
    env_file:
      - .env
    networks:
      - smtp-app
  postgresdb:
    image: postgres
    container_name: postgres-smtp-app-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .db.env
    networks:
      - smtp-app
    volumes:
      - postgres-smtp-app-db:/var/lib/postgresql/data
volumes:
  postgres-smtp-app-db:
    name: backend-db
networks:
  smtp-app:
    driver: bridge
